### ISSUE TITLE
Initial Project Setup

### ISSUE THREAD

**Issue by krisstanton** [NASA-IMPACT/csda-publication-usage-finder#1]
Set up this repo, condense notes, begin edits on readme file, plan project goals, create a plan of action to progress forward.

- [x] Loosely Plan Initial Object Models
- [x] Draw initial Architecture (code and interactions with the web)
- [x] Research potential websites to target
- [x] Research potential libraries to use to achieve the goals

**Comment by krisstanton** [comment]
Work In Progress Update: After some initial research, it looks as though Google Scholars does not have an official API.  It also seems that Google Scholars will IP ban anyone trying to utilize web scrapping scripts.
One viable alternative is to connect and code in several APIs that are meant for doing publication searches, and then combine their results.
Theoretically, we could still build a direct web-scrapping portion of this application, but this would come with some risks.  If we are going to do that, we should not solely depend on that approach.

**Comment by simha4** [comment]
Okay Kris, we’ll discuss about this when we meet.
