### ISSUE TITLE
Handle Storage of previous runs - Logic

### ISSUE THREAD

**Issue by krisstanton** [NASA-IMPACT/csda-publication-usage-finder#10]
When this application is run, it generates some outputs.
When the application is run again, we need to reference the previously generated outputs and perform operations with those.

- [x] Convert python dictionary object to JSON
- [x] During report generation, be able to load this previously run data and compare with the current results for the report.
- - [x] Make sure this works for local runs
- - [ ] Make sure this works for cloud runs

**Comment by simha4** [comment]
Handle storage of previous runs specific to Cloud is being carried out in #12.
