### ISSUE TITLE
Publication API Research

### ISSUE THREAD

**Issue by krisstanton** [NASA-IMPACT/csda-publication-usage-finder#3]
Research the various Publication APIs.
Here is an initial list of Publication Search APIs I found after some checking.
https://guides.temple.edu/APIs#:~:text=An%20API%20is%20a%20protocol,the%20corpus%20they've%20downloaded.
(Note: Some of the below questions are already answered on this page)
The initial goal here is to have 1 or 2 highly reliable APIs to start with that may generate positive results.

Also Note: There is a 3rd party api for Google Scholar called SerpAPI that should also be examined. https://serpapi.com/google-scholar-api

For each of the above APIs we need to get an understanding of what kind of limitations may exist.
Here is a starter list of things to look for, for each API - Note: Not all of these list items and follow up questions are expected to have answers for every API
- [x] Cost, is this API Free?  If it is, is it always free?  If it is not free, is there a free version that is limited? If not, how much does it cost?
- [ ] What is the complexity / process for getting an API Key or regular API Access?  Is there simply an HTTP request we can make?  Do we need to mess around with Auth Tokens?  Do we need to get a new key every so often?
- [x] Rate Limits: Are we limited to a certain amount of requests per time period (ex: 5 requests per second, or 1000 requests per month, etc), we need to know this so we don't overuse any of these APIs in development or production environments
- [ ] Would an Earth Science Publication show up here?  Content Limitations?  I noticed that some Publication Searches are limited to certain scientific disciplines.  We would probably not expect to find an Earth Science Publication in a biomedical journal (although that kind of cross over is something we should later consider as a possibility)

**Comment by krisstanton** [comment]
Just in case the link above stops working, Here is a copy and paste of the important contents from that page.

"

List of APIs for Scholarly Research
[arXiv](https://arxiv.org/help/api/index)
Content: metadata and article abstracts for the e-prints hosted on arXiv.org
Permissions: no registration required
Limitations: no more than 4 requests per second
Contact: https://groups.google.com/forum/#!forum/arxiv-api, https://arxiv.org/help/api/index
 

[Astrophysics Data System](http://adsabs.github.io/help/api/)
Content: bibliographic data on astronomy and physics publications from SAO/NASA astrophysics databases
Permissions: free to register; request a key at [https://github.com/adsabs/adsabs-dev-api](https://github.com/adsabs/adsabs-dev-api%E2%80%8B)
Limitations: varies
Contact: https://groups.google.com/forum/#!forum/adsabs-dev-api, adshelp@cfa.harvard.edu
 

[BioMed Central](https://www.biomedcentral.com/getpublished/indexing-archiving-and-access-to-data#api)
Content: metadata and full-text content for open access journals published in BioMed Central
Permissions: free to access, request a key at https://dev.springer.com/signup
Limitations: none
Contact: [i](mailto:info@biomedcentral.com)nfo@biomedcentral.com
 

[Chronicling America](https://chroniclingamerica.loc.gov/about/api/)
Content: digitized newspapers from 1789-1963, as well as a directory of newspapers published 1960 to the present, with information on library holdings
Permissions: no registration required
Limitations: none
Contact: http://www.loc.gov/rr/askalib/ask-webcomments.html
 

[CORE](https://core.ac.uk/services/api/)
Content: metadata and full-text of over 100 million OA research papers
Permissions: free to access for non-commercial purposes, request a key at https://core.ac.uk/api-keys/register
Limitations: One batch request or five single requests every 10 seconds. Contact CORE if you need a faster rate.
Contact: theteam@core.ac.uk
 

[CrossRef](https://www.crossref.org/education/retrieve-metadata/rest-api/a-non-technical-introduction-to-our-api/)
Content: metadata records with CrossRef DOIs, over 100 million scholarly works
Permissions: no registration required
Limitations: guidelines to avoid overloading the servers at https://github.com/CrossRef/rest-api-doc#meta. "We reserve the right to impose rate limits and/or to block clients that are disrupting the public service."
Contact: labs@crossref.org
 

[Digital Public Library of America](https://dp.la/info/developers/codex/requests/)
Content: metadata on items and collections indexed by the DPLA
Permissions: request a free key; instructions here https://pro.dp.la/developers/policies
Limitations: none, however, "The DPLA reserves the right to limit or revoke access to the API if, in its discretion, a user engages in abusive conduct, conduct that materially degrades the ability of other users to query the API."
Contact: codex@dp.la
 

[Elsevier](https://dev.elsevier.com/index.html)
Content: multiple APIs for full-text books and journals from ScienceDirect and citation data from Engineering Village and Embase
Permissions: free to register; click 'Get API Key" to request a personal key: https://dev.elsevier.com/
Limitations: "Researchers at subscribing academic institutions can text mine subscribed full-text ScienceDirect content via the Elsevier APIs for non-commercial purposes."   Usage policies depend on use cases; see list at https://dev.elsevier.com/use_cases.html
Contact: integrationsupport@elsevier.com

 

[HathiTrust (Bibliographic API)](https://www.hathitrust.org/bib_api)
Content: bibliographic and rights information for items in the HathiTrust Digital Library
Permissions: no registration required
Limitations: may request up to 20 records at once. Not intended for bulk retrieval
Contact: feedback@issues.hathitrust.org
 

[HathiTrust (Data API)](https://www.hathitrust.org/data_api)
Content: full-text of HathiTrust and Google digitized texts of public domain works
Permissions: free to access, request a key at https://babel.hathitrust.org/cgi/kgs/request
Limitations: "Please contact [HathiTrust] to determine the suitability of the API for intended uses."
Contact: feedback@issues.hathitrust.org
 

[IEEE Xplore](https://developer.ieee.org/getting_started)
Content: metadata for articles included in IEEE Xplore
Permissions: must be affiliated with an institution that subscribes to IEEE Xplore. Temple is a subscriber.
Limitations: maximum 1,000 results per query
Contact: onlinesupport@ieee.org
 

[JSTOR](https://www.jstor.org/dfr/)
Content: full-text articles from JSTOR
Permissions:  free to use, register at https://www.jstor.org/dfr/
Limitations:  Not a true API, but allows users to construct a search and then download the results as a dataset for text-mining purposes. Can download up to 25,000 documents. Largest datasets available by special request
Contact: https://support.jstor.org/hc/en-us
 

[National Library of Medicine](https://eresources.nlm.nih.gov/nlm_eresources/)
Content: 60 separate APIs for accessing various NLM databases, including PubMed Central, ToxNet, and ClinicalTrials.gov. The PubMed API is listed separately below.
Permissions: varies
Limitations: varies
Contact: varies
 

[Nature.com OpenSearch](https://www.nature.com/opensearch/)
Content: bibliographic data for content hosted on Nature.com, including news stories, research articles and citations
Permissions: free to access
Limitations: varies
Contact: interfaces@nature.com
 

[OECD](https://data.oecd.org/api/)
Content: a selection of the top used datasets covering data for OECD countries and selected non-member economies. Datasets included appear in the [catalogue of OECD databases with API access](https://data.oecd.org/searchresults/?hf=20&b=0&r=f%2Ftype%2Fdatasets%2Fapi+access&r=%2Bf%2Ftype%2Fdatasets%2Fapi+access&l=en&s=score)
Permissions: no registration required, see [terms and conditions](http://www.oecd.org/termsandconditions/)
Limitations: max 1,000,000 results per query, max URL length of 1,000 characters.
Contact: OECDdotStat@oecd.org
 

[ORCID Public API](https://info.orcid.org/documentation/features/public-api/)
Content: metadata from public ORCID persistant researcher identifier profiles.
Permissions: [registration required](https://orcid.org/register), see [the public client terms of service](https://info.orcid.org/public-client-terms-of-service/)
Limitations: max 10,000 results per query
Contact: [Submit an ORCID support request](https://support.orcid.org/hc/en-us/requests/new)
 

[PLOS Search API](http://api.plos.org/solr/)
Content: full-text of research articles in PLOS journals
Permissions: free to access, register at http://api.plos.org/registration/
Limitations: Max is 7200 requests a day, 300 per hour, 10 per minute. Users should wait 5 seconds for each query to return results. Requests should not return more than 100 rows. High-volume users should contact api@plos.org. API users are limited to no more than five concurrent connections from a single IP address.
Contact: api@plos.org
 

[PubMed](https://www.ncbi.nlm.nih.gov/books/NBK25500/)
Content: information stored in 38 NCBI databases, including some info from PubMed. Will retrieve a PubMed ID when citation information is input.
Permissions: API key required starting May 1, 2018
Limitations: After May 1, 2018, with an API key a site can post up to 10 requests per second by default. Large jobs should be limited to outside 9-5 weekday hours. Higher rates are available by request (see contact information below)
Contact: eutilities@ncbi.nlm.nih.gov[​](http://adsabs.github.io/help/api/)
 

[Springer](https://dev.springer.com/)
Content: full-text of SpringerOpen journal content and BioMed Central, as well as metadata from other Springer resources
Permissions: free to access, request a key at https://dev.springer.com/signup
Limitations: noncommercial use
Contact: tdm@springernature.com
 

[World Bank APIs](https://datahelpdesk.worldbank.org/knowledgebase/articles/889386-developer-information-overview)
Content: APIs for the following datasets: Indicators (time series data), Projects (data on the World Bank’s operations), and World Bank financial data (World Bank Finances API)
Permissions: no registration required
Limitations: See [Terms & Conditions of Using our Site](http://www.worldbank.org/en/about/legal/terms-and-conditions)
Contact: data@worldbankgroup.org

"

**Comment by simha4** [comment]
[API slection.docx](https://github.com/NASA-IMPACT/csda-publication-usage-finder/files/13479672/API.slection.docx)
Here's the document for initial research on API selection.
